---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-kenmoini-multiverse-of-multicluster-madness
  namespace: rhacm-channels
spec:
  type: Git
  pathname: 'https://github.com/kenmoini/multiverse-of-multicluster-madness'
  insecureSkipVerify: true
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-kenmoini-gitops-for-me-and-you
  namespace: rhacm-channels
spec:
  type: Git
  pathname: 'https://github.com/kenmoini/gitops-for-me-and-you'
  insecureSkipVerify: true