apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: rhacm-geo-hub-deployed-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: rhacm-geo-hub-deployed-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: geo-hub-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - rhacm-hub-deployed
policies:
  - name: rhacm-geo-hub-deployed
    manifests:
      - path: manifests
        patches:
          - apiVersion: operator.open-cluster-management.io/v1
            kind: MultiClusterHub
            metadata:
              name: multiclusterhub
              namespace: open-cluster-management
            spec:
            # https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/install/installing#installing-on-infra-node
              tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Exists
                - effect: NoExecute
                  key: node-role.kubernetes.io/infra
                  operator: Exists
              nodeSelector:
                node-role.kubernetes.io/infra: ""
              disableHubSelfManagement: true
