apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/gitops-for-you-and-me.git'
    targetRevision: HEAD
    ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
    path: manifests/external-secrets
    ## Enable recursive sub-directory search to enable management of multiple cluster from this single Application
    directory:
      recurse: true
  project: hub-cluster-apps
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      #selfHeal: false # overrides changes made on the cluster that drift from git state