---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 'system:openshift:scc:privileged'
  namespace: reflector
subjects:
  - kind: ServiceAccount
    name: default
    namespace: reflector
  - kind: ServiceAccount
    name: reflector
    namespace: reflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'