apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: openshift-gitops
spec:
  project: helm-installed
  source:
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: v6.1.47
    helm:
      releaseName: reflector
      #valueFiles:
      #- values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reflector
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state
    syncOptions:
      - CreateNamespace=true