apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: hub-argocd-rbac
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/gitops-for-you-and-me.git'
    targetRevision: HEAD
    path: 5-argocd/rbac
    #directory:
    #  recurse: true
    kustomize:
      version: v4.4.1
  project: hub-cluster-apps
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false # overrides changes made on the cluster that drift from git state
    syncOptions:
      - CreateNamespace=true
