---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rhacs-operator-installed-pb
  namespace: rhacm-policies
placementRef:
  name: all-openshift-clusters
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: rhacs-operator-installed
    apiGroup: policy.open-cluster-management.io
    kind: Policy