---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-redis-enterprise-operator-administrators
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: abradhak@redhat.com
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: nupadhya@redhat.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-enterprise-operator-admin
