---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hub-argocd-rbac
- reflector-chart-installed
- install-rhacm-operator
- deploy-rhacm-hub
- hoh-rhacm-base-config
#- rhacm-applications
#- rhacm-channels
#- rhacm-observability
#- rhacm-policies
#- external-secrets
#- sealedsecrets-chart-installed