apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: additional-trust-bundle-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: additional-trust-bundle-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: all-openshift-clusters
  #  name: demo-placement-rule
  #  clusterSelectors:
  #    name: not-local-cluster
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets: 
  #  - global-base-configuration
policies:
  - name: additional-trust-bundles
    manifests:
      - path: base
