---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spoke-clusters
  namespace: rhacm-policies
spec:
  clusterSelector:
    matchExpressions:
      - key: cluster-role
        operator: In
        values:
          - spoke-cluster
  clusterConditions: []
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spoke-clusters
  namespace: rhacm-applications
spec:
  clusterSelector:
    matchExpressions:
      - key: cluster-role
        operator: In
        values:
          - spoke-cluster
  clusterConditions: []
