---
# This openshift-gitops-policy-admin CRB binds the openshift-gitops-argocd-application-controller SA to the openshift-gitops-policy-admin role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-external-secrets
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-external-secrets