---
kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  #annotations:
    #acme.org/sha: 1234
  #labels:
    #acme.org/owned-by: q-team
  name: pull-secret
  namespace: open-cluster-management
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hub-vault
  data:
    - secretKey: .dockerconfigjson # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hub-pull-secret # name of the secret under the target Vault path
        property: dockerconfigjson # # name of the key in that named Vault secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pull-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
---
kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  #annotations:
    #acme.org/sha: 1234
  #labels:
    #acme.org/owned-by: q-team
  name: pull-secret
  namespace: multicluster-engine
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: hub-vault
  data:
    - secretKey: .dockerconfigjson # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: hub-pull-secret # name of the secret under the target Vault path
        property: dockerconfigjson # # name of the key in that named Vault secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pull-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
---
#kind: ExternalSecret
#apiVersion: external-secrets.io/v1beta1
#metadata:
#  #annotations:
#    #acme.org/sha: 1234
#  #labels:
#    #acme.org/owned-by: q-team
#  name: pull-secret
#  namespace: hive
#spec:
#  refreshInterval: 10m
#  secretStoreRef:
#    kind: ClusterSecretStore
#    name: hub-vault
#  data:
#    - secretKey: .dockerconfigjson # the key to be made in this k8s Secret
#      remoteRef:
#        conversionStrategy: Default
#        decodingStrategy: None
#        key: hub-pull-secret # name of the secret under the target Vault path
#        property: dockerconfigjson # # name of the key in that named Vault secret
#  target:
#    creationPolicy: Owner
#    deletionPolicy: Retain
#    name: pull-secret
#    template:
#      engineVersion: v2
#      type: kubernetes.io/dockerconfigjson
