apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: install-gitops-operator-pg
  namespace: rhacm-applications
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - install-gitops-operator-pg
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 5-rhacm/policy-generators/install-openshift-gitops-operator
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: install-gitops-operator-pg
  name: install-gitops-operator-pg
  namespace: rhacm-applications
spec:
  channel: rhacm-channels/ggithubcom-kenmoini-gitops-for-me-and-you
  placement:
    placementRef:
      kind: PlacementRule
      name: management-clusters
