---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00_namespace.yml
  - 03_rbac.yml
  - 05_operatorgroup.yml
  - 10_subscription.yml
  - ../../../../5-argocd/appProjects/
  - ../../../../5-argocd/rbac/
  #- ../../../../2-bootstrap-gitops/01_deploy-openshift-gitops/
